version: '3'
services:
  mongodb:
    image: mongo:latest
    container_name: mongo-pritunl
    expose:
      - "27017"
    volumes:
      - ./data/mongo:/data/db
    restart: always

  pritunl:
    image: jqtype/pritunl
    container_name: pritunl
    restart: always
    env_file:
      - pritunl.env
    ports:
      - 80:80 # web
      - 443:443 # web
      - 9700:9700 # web
      - 1194:1194/udp # openvpn
    tty: true
    privileged: true
    volumes:
      - ./data/pritunl:/var/lib/pritunl
      - ./log/pritunl:/var/log/pritunl
    links:
      - mongodb
    depends_on:
      - mongodb